# Generated by Django 5.2.7 on 2025-11-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockupimage',
            name='image',
        ),
        migrations.AddField(
            model_name='mockupimage',
            name='url',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
