# Generated by Django 5.2.7 on 2025-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0002_remove_mockupimage_image_mockupimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('RETRY', 'Retry'), ('FAILURE', 'Failure'), ('SUCCESS', 'Success')], max_length=20)),
            ],
        ),
    ]
