# Generated by Django 5.2.7 on 2025-11-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0003_mockuptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockupimage',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mockuper.mockuptask'),
        ),
    ]
