# Generated by Django 5.2.7 on 2025-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0004_mockupimage_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptask',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
    ]
