# Generated by Django 5.2.7 on 2025-11-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0005_alter_mockuptask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('RETRY', 'Retry'), ('FAILURE', 'Failure'), ('SUCCESS', 'Success')], default='PENDING', max_length=20),
        ),
    ]
