# Generated by Django 5.2.7 on 2025-11-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0006_alter_mockuptask_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockuptask',
            old_name='task_id',
            new_name='task_uuid',
        ),
    ]
