# Generated by Django 5.2.7 on 2025-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0007_rename_task_id_mockuptask_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockupimage',
            name='color',
            field=models.CharField(default='red', max_length=150),
        ),
    ]
