# Generated by Django 5.2.7 on 2025-11-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockuper', '0008_mockupimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockupimage',
            name='font',
            field=models.CharField(default='roboto', max_length=150),
        ),
    ]
